
enum ConfigProperties {
  SEND_REAL_SMS = 'SEND_REAL_SMS',
  ESCROW_CHARGE_PERCENTAGE = 'ESCROW_CHARGE_PERCENTAGE',
  CINDERBUILD_REVENUE_PERCENTAGE = 'CINDERBUILD_REVENUE_PERCENTAGE',
  ORDER_PAYMENT_DEFAULT_DAILY_CHARGE_PERCENTAGE = 'ORDER_PAYMENT_DEFAULT_DAILY_CHARGE_PERCENTAGE',
  COOPERATE_ACCOUNT_DISCOUNT = 'COOPERATE_ACCOUNT_DISCOUNT',
  VAT = "VAT",
  C_STORE_DEFAULT_PAYMENT_CHARGE_PERCENTAGE = "C_STORE_DEFAULT_PAYMENT_CHARGE_PERCENTAGE"

}

export default ConfigProperties
