/* eslint-disable no-shadow */
export enum OrderStatuses {
  CREATED = 'CREATED',
  IN_PROGRESS = 'IN_PROGRESS',

  AVAILABLE_FOR_PICKUP = 'AVAILABLE_FOR_PICKUP',
  AVAILABLE_FOR_DELIVERY = 'AVAILABLE_FOR_DELIVERY',

  RECEIVED = 'RECEIVED',
  
  COMPLETED = 'COMPLETED', // to be set by the seller
  CONFIRMED = 'CONFIRMED', // to be set by the buyer after the seller has set completed
  CONFIRMED_BY_SYSTEM = 'CONFIRMED_BY_SYSTEM',
  
  CANCELLED_BY_BUYER = 'CANCELLED_BY_BUYER',
  CANCELLED_BY_SELLER = 'CANCELLED_BY_SELLER',
  CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN',

  ENDED_WITH_DISPUTES = 'ENDED_WITH_DISPUTES',
  PAYMENT_DEFAULT = 'PAYMENT_DEFAULT',
}

export enum OrderStatusesDto {
  ALL = 'ALL',
  CREATED = 'CREATED',
  IN_PROGRESS = 'IN_PROGRESS',

  AVAILABLE_FOR_PICKUP = 'AVAILABLE_FOR_PICKUP',

  AVAILABLE_FOR_DELIVERY = 'AVAILABLE_FOR_DELIVERY',
  
  RECEIVED = 'RECEIVED',

  COMPLETED = 'COMPLETED',
  CONFIRMED = 'CONFIRMED',
  CONFIRMED_BY_SYSTEM = 'CONFIRMED_BY_SYSTEM',
  
  CANCELLED_BY_BUYER = 'CANCELLED_BY_BUYER',
  CANCELLED_BY_SELLER = 'CANCELLED_BY_SELLER',
  CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN',
  
  ENDED_WITH_DISPUTES = 'ENDED_WITH_DISPUTES',
  PAYMENT_DEFAULT = 'PAYMENT_DEFAULT',
}

export const ActiveOrderStatuses: OrderStatuses[] = [
  OrderStatuses.CREATED, 
  OrderStatuses.IN_PROGRESS, 
  OrderStatuses.AVAILABLE_FOR_PICKUP, 
]

export const EndedOrderStatuses: OrderStatuses[] = [
  OrderStatuses.COMPLETED,
  OrderStatuses.CONFIRMED,
  OrderStatuses.ENDED_WITH_DISPUTES,

  OrderStatuses.CANCELLED_BY_BUYER,
  OrderStatuses.CANCELLED_BY_SELLER,
  OrderStatuses.CANCELLED_BY_ADMIN
]

export enum QuoteRequestStatuses {
  PENDING = "PENDING",
  PROCESSED = "PROCESSED", // Means seller has responded

  CANCELLED_BY_BUYER = "CANCELLED_BY_BUYER", // Means buyer cancelled before seller responded
  ENDED_BY_BUYER = "ENDED_BY_BUYER", // Means buyer cancelled AFTER seller responded
  ORDER_CREATED = "ORDER_CREATED",

  DECLINED_BY_SELLER = "DECLINED_BY_SELLER",
  DECLINED_BY_ADMIN = "DECLINED_BY_ADMIN",
  EXPIRED = "EXPIRED",
}

export enum PriceMatriceStatuses {
  CREATED = 'CREATED',
  PRICE_SUBMITTED = 'PRICE_SUBMITTED',
  APPROVED = 'APPROVED',
  DELIVERED = 'DELIVERED',
  CONFIRMED_DELIVERY = 'CONFIRMED_DELIVERY',
  SELLER_PAID = 'SELLER_PAID',
  DECLINED = 'DECLINED',
  DECLINED_BY_ADMIN = "DECLINED_BY_ADMIN",
}

export enum OrderDeliveryLocationStatuses {
  PENDING = 'PENDING',
  LOADING = 'LOADING',
  IN_TRANSIT = 'IN_TRANSIT',
  ON_SITE = 'ON_SITE',

  DISCHARGE_REQUESTED = 'DISCHARGE_REQUESTED',
  DISCHARGE_REQUEST_CONFIRMED = 'DISCHARGE_REQUEST_CONFIRMED',

  DELIVERY_CONFIRMATION_REQUESTED = 'DELIVERY_CONFIRMATION_REQUESTED',
  DELIVERY_CONFIRMED = 'DELIVERY_CONFIRMED',
  DELIVERY_DISPUTE = 'DELIVERY_DISPUTE',
}


export enum OrderPaymentStatuses {
  BUYER_PAYMENT_PENDING = 'BUYER_PAYMENT_PENDING',
  BUYER_PAYMENT_IN_ESCROW = 'BUYER_PAYMENT_IN_ESCROW',
  BUYER_PAYMENT_REFUND = 'BUYER_PAYMENT_REFUND',
  ESCROW_FUNDS_MOVED_TO_SELLER = 'ESCROW_FUNDS_MOVED_TO_SELLER',
  CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN',
}

export enum OrderPaymentStatusesDto {
  ALL = 'ALL',
  BUYER_PAYMENT_PENDING = 'BUYER_PAYMENT_PENDING',
  BUYER_PAYMENT_IN_ESCROW = 'BUYER_PAYMENT_IN_ESCROW',
  BUYER_PAYMENT_REFUND = 'BUYER_PAYMENT_REFUND',
  ESCROW_FUNDS_MOVED_TO_SELLER = 'ESCROW_FUNDS_MOVED_TO_SELLER',
}

export enum OrderPaymentVariantDto {
  ALL = 'ALL',
  WALLET = 'WALLET',
  CARD = 'CARD',
  PAY_ON_DELIVERY = 'PAY_ON_DELIVERY'
}

export enum WareHouseToSiteDeliveryFeeStatuses {
  REQUESTED = 'REQUESTED',
  DELIVERY_FEE_SET = 'DELIVERY_FEE_SET',
  DELIVERY_FEE_ACCEPTED = 'DELIVERY_FEE_ACCEPTED',
  DELIVERY_FEE_REJECTED = 'DELIVERY_FEE_REJECTED',
  DELIVERY_ITEMS_SHIPPED = 'DELIVERY_ITEMS_SHIPPED',
}

export enum InvoiceStatuses {
  SET = 'SET',
  ACCEPTED = 'ACCEPTED',
  REQUEST_REVIEW = 'REQUEST_REVIEW',
  REJECTED = 'REJECTED',
}

export enum MonoWebhookStatus {
  SUCCESSFULL = 'successful',
  FAILED = 'failed'
}

export default OrderStatuses
