export const SHOW_LOADING_MODAL = 'SHOW_LOADING_MODAL'
export const SIDE_BAR_TOGGLE = 'SIDE_BAR_TOGGLE'

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ATTEMPT_FAIL = 'LOGIN_ATTEMPT_FAIL'

export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ATTEMPT_FAIL = 'SIGNUP_ATTEMPT_FAIL'
